volumes:
  rabbitmq:
  mysql:

services:
  # The APP's business logic
  hedge-btc:
    depends_on:
      - rabbitmq
    image: hedge
    container_name: hedge-btc
    build: .
    command: ["start", "BTCFDUSD"]
    volumes:
      - .:/srv

  hedge-bnb:
    depends_on:
      - rabbitmq
    image: hedge
    container_name: hedge-bnb
    build: .
    command: ["start", "BNBFDUSD"]
    volumes:
      - .:/srv

  telegram:
    depends_on:
      - rabbitmq
      - mysql
    image: hedge
    container_name: telegram
    build: .
    command: ["telegram:start"]
    volumes:
      - .:/srv

  # subscribe to websockets and publish trades to AMQP
  tradefeed:
    image: hedge
    container_name: tradefeed
    build: .
    command: ["tradefeed", "ETHFDUSD", "BTCFDUSD", "BNBFDUSD"]
    restart: on-failure
    depends_on:
      - rabbitmq
    volumes:
      - .:/srv

  # on-demand notify user if price moved
  monitor-range:
    image: hedge
    container_name: monitor-range
    build: .
    command: ["monitor:range"]
    depends_on:
      - rabbitmq
    volumes:
      - .:/srv

  # record trades to database for backtesting
  db:
    depends_on:
      - rabbitmq
      - mysql
    image: hedge
    container_name: db
    build: .
    command: ["db"]
    restart: on-failure
    volumes:
      - .:/srv

  # AMQP message queue to enable multitasking in PHP
  rabbitmq:
    hostname: rabbitmq # must be defined for data durability so that db file has always same name
    container_name: rabbitmq
    image: rabbitmq:3-management
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  # database and GUI for it
  mysql:
    image: mysql:8
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/hedge.sql:ro
      - ./telegram.sql:/docker-entrypoint-initdb.d/telegram.sql:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}
